### ISSUE TITLE
go install failed

### ISSUE THREAD

**Issue by emirgra** [aydinnyunus/PackageSpy#2]
sanırım https://github.com/aydinnyunus/PackageSpy?tab=readme-ov-file#installation kısmını da değiştirmek gerekiyor. zannediyorum yeni bir release lazım. kolay gelsin.

![yunus_aydin_packagespy_failed](https://github.com/aydinnyunus/PackageSpy/assets/34007081/0c55f5d1-575c-4dd2-aaba-1acda04b4440)

**Comment by aydinnyunus** [comment]
Yeni release'i çıktım tekrar deneyebilir misin

**Comment by emirgra** [comment]
düzeldi teşekkürler. fakat bu sefer de başka bir arıza çıktı. `--search` flag'ı çalışmıyor.

```
➜  Desktop PackageSpy scan --search datascience --pypi
Error: unknown flag: --search
Usage:
  PackageSpy scan [flags]

Flags:
  -h, --help              help for scan
  -n, --npm               is NPM
  -p, --pypi              is PyPI
  -u, --username string   Username for Package Manager
```

**Comment by aydinnyunus** [comment]
Bir release daha çıktım

**Comment by emirgra** [comment]
şuan arıza giderildi. eline sağlık. mesela `scan --search datascience --pypi` kullanınca pypi'da datascience ile ilgili arama yapıp çıkan ilk paketi inidirip onun üzerinde arama yapıyor. belki biraz daha geliştirilse daha güzel olabilir. fikir vermek açısından `https://snyk.io/advisor/python` bu site yardımcı olabilir. kolay gelsin.

**Comment by aydinnyunus** [comment]
aslında şuan loopta tüm sayfaları geziyor. yani ilk paketi indirmiyor. eğer feature request varsa onu da bir issue olarak açabilirsin

**Comment by aydinnyunus** [comment]
ilgin için teşekkürler
