### ISSUE TITLE
Default content

### ISSUE THREAD

**Issue by fabaff** [aydinnyunus/PackageSpy#4]
IMHO, it would improve the user experience if the content is updated.

https://github.com/aydinnyunus/PackageSpy/blob/74125411c873039523cb65df75ea42093287de2e/cmd/root.go#L15-L21

**Comment by aydinnyunus** [comment]
Thank you for your attention. I update the short and long descriptions.

https://github.com/aydinnyunus/PackageSpy/blob/main/cmd/root.go#L14-L19
